version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - build

jobs:
  build:
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
